from __future__ import annotations

from aiohttp import web


def register(app: web.Application, server) -> None:
    app.router.add_get("/api/admin/bots", server.admin_bots)
    app.router.add_get("/api/admin/assets/avatars", server.admin_list_avatar_assets)
    app.router.add_get("/api/admin/bots/{alias}/processing", server.admin_processing)
    app.router.add_post("/api/admin/bots", server.admin_add_bot)
    app.router.add_get("/api/admin/bots/{alias}", server.admin_single_bot)
    app.router.add_delete("/api/admin/bots/{alias}", server.admin_remove_bot)
    app.router.add_post("/api/admin/bots/{alias}/start", server.admin_start_bot)
    app.router.add_post("/api/admin/bots/{alias}/stop", server.admin_stop_bot)
    app.router.add_get("/api/bots/{alias}/cli-params", server.get_cli_params)
    app.router.add_patch("/api/bots/{alias}/cli-params", server.patch_cli_params)
    app.router.add_post("/api/bots/{alias}/cli-params/reset", server.post_cli_params_reset)
    app.router.add_patch("/api/admin/bots/{alias}/cli", server.admin_update_cli)
    app.router.add_patch("/api/admin/bots/{alias}/alias", server.admin_rename_bot)
    app.router.add_patch("/api/admin/bots/{alias}/workdir", server.admin_update_workdir)
    app.router.add_patch("/api/admin/bots/{alias}/avatar", server.admin_update_avatar)
    app.router.add_patch("/api/admin/bots/{alias}/prompt-presets", server.admin_update_prompt_presets)
    app.router.add_patch("/api/admin/prompt-presets/global", server.admin_update_global_prompt_presets)
    app.router.add_get("/api/admin/update", server.admin_get_update)
    app.router.add_patch("/api/admin/update", server.admin_patch_update)
    app.router.add_post("/api/admin/update/check", server.admin_update_check)
    app.router.add_post("/api/admin/update/download", server.admin_update_download)
    app.router.add_post("/api/admin/update/download/stream", server.admin_update_download_stream)
    app.router.add_get("/api/admin/update/offline-packages", server.admin_update_offline_packages)
    app.router.add_get("/api/admin/update/offline/packages", server.admin_update_offline_packages)
    app.router.add_post("/api/admin/update/offline/prepare", server.admin_update_offline_prepare)
    app.router.add_post("/api/admin/update/offline/prepare/stream", server.admin_update_offline_prepare_stream)
    app.router.add_get("/api/admin/env", server.admin_env_get)
    app.router.add_patch("/api/admin/env", server.admin_env_patch)
    app.router.add_post("/api/admin/env/reload-preview", server.admin_env_reload_preview)
    app.router.add_post("/api/admin/restart", server.admin_restart)
    app.router.add_get("/api/admin/tunnel", server.admin_tunnel)
    app.router.add_post("/api/admin/tunnel/start", server.admin_tunnel_start)
    app.router.add_post("/api/admin/tunnel/stop", server.admin_tunnel_stop)
    app.router.add_post("/api/admin/tunnel/restart", server.admin_tunnel_restart)
