from __future__ import annotations

from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Protocol

from bot.debug.models import DebugProfile


@dataclass(frozen=True)
class DebugProviderEvent:
    type: str
    payload: dict[str, object] = field(default_factory=dict)

    def to_api(self) -> dict[str, object]:
        return {"type": self.type, "payload": dict(self.payload)}


class DebugProviderError(RuntimeError):
    def __init__(self, code: str, message: str, *, detail: str = "", data: dict[str, object] | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.detail = detail
        self.data = dict(data or {})


class DebugProviderSession(Protocol):
    async def launch(self, payload: dict[str, object]) -> None: ...
    async def stop(self) -> None: ...
    async def continue_execution(self) -> None: ...
    async def pause(self) -> None: ...
    async def next(self) -> None: ...
    async def step_in(self) -> None: ...
    async def step_out(self) -> None: ...
    async def set_breakpoints(self, source: str, breakpoints: list[dict[str, object]]) -> list[dict[str, object]]: ...
    async def stack_trace(self) -> list[dict[str, object]]: ...
    async def scopes(self, frame_id: str) -> list[dict[str, object]]: ...
    async def variables(self, variables_reference: str) -> list[dict[str, object]]: ...
    async def evaluate(self, expression: str, frame_id: str = "") -> dict[str, object]: ...
    async def events(self) -> AsyncIterator[dict[str, object]]: ...
    async def close(self) -> None: ...


class DebugProvider(Protocol):
    provider_id: str
    provider_label: str

    def can_handle(self, profile: DebugProfile) -> bool: ...
    def create_session(self, profile: DebugProfile) -> DebugProviderSession: ...
