"""Assistant admin Web service compatibility facade."""

from __future__ import annotations

from bot.web.api_service import (
    approve_assistant_proposal,
    approve_assistant_proposal_patch,
    apply_assistant_upgrade,
    bulk_invalidate_assistant_memories,
    create_assistant_cron_job,
    delete_assistant_cron_job,
    dry_run_assistant_upgrade,
    generate_assistant_proposal_patch,
    get_assistant_diagnostics,
    get_assistant_proposal_detail,
    get_assistant_upgrade_apply_log,
    invalidate_assistant_memory,
    list_assistant_cron_jobs,
    list_assistant_cron_runs,
    list_assistant_memory_eval_reports,
    list_assistant_proposals,
    list_assistant_upgrade_targets,
    reindex_assistant_memory,
    reject_assistant_proposal,
    run_assistant_cron_job_now,
    run_assistant_memory_eval_task,
    search_assistant_memories,
    stream_generate_assistant_proposal_patch,
    update_assistant_cron_job,
)

__all__ = [
    "approve_assistant_proposal",
    "approve_assistant_proposal_patch",
    "apply_assistant_upgrade",
    "bulk_invalidate_assistant_memories",
    "create_assistant_cron_job",
    "delete_assistant_cron_job",
    "dry_run_assistant_upgrade",
    "generate_assistant_proposal_patch",
    "get_assistant_diagnostics",
    "get_assistant_proposal_detail",
    "get_assistant_upgrade_apply_log",
    "invalidate_assistant_memory",
    "list_assistant_cron_jobs",
    "list_assistant_cron_runs",
    "list_assistant_memory_eval_reports",
    "list_assistant_proposals",
    "list_assistant_upgrade_targets",
    "reindex_assistant_memory",
    "reject_assistant_proposal",
    "run_assistant_cron_job_now",
    "run_assistant_memory_eval_task",
    "search_assistant_memories",
    "stream_generate_assistant_proposal_patch",
    "update_assistant_cron_job",
]
